import type { IconType } from "react-icons";
import * as Fa6 from "react-icons/fa6";

/**
 * Content lives in MongoDB, so an icon has to travel as a plain string rather
 * than a component reference. This registry is the single place that turns one
 * back into a component, and doubles as the list the admin icon picker offers.
 *
 * Only the names listed here are bundled — importing the whole of `react-icons`
 * is not an option, so an icon the admin should be able to pick has to be added
 * to one of the groups below.
 */
const {
  FaAndroid,
  FaAngular,
  FaArrowRight,
  FaArrowUpRightFromSquare,
  FaArrowsRotate,
  FaAward,
  FaAws,
  FaBolt,
  FaBoxesStacked,
  FaBrain,
  FaBriefcase,
  FaBuilding,
  FaBuildingColumns,
  FaBullhorn,
  FaBullseye,
  FaCalendarCheck,
  FaCamera,
  FaCar,
  FaCartShopping,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckDouble,
  FaCircleCheck,
  FaCirclePlay,
  FaClock,
  FaCloud,
  FaCode,
  FaComments,
  FaCss3Alt,
  FaCube,
  FaDatabase,
  FaDocker,
  FaDollarSign,
  FaEarthAmericas,
  FaEnvelope,
  FaEye,
  FaFacebookF,
  FaFeather,
  FaFilm,
  FaFire,
  FaFolderOpen,
  FaGamepad,
  FaGaugeHigh,
  FaGears,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGoogle,
  FaGraduationCap,
  FaHandPointer,
  FaHandshake,
  FaHeadset,
  FaHeart,
  FaHospital,
  FaHotel,
  FaHouse,
  FaHtml5,
  FaIndustry,
  FaInstagram,
  FaJava,
  FaJs,
  FaLaptopCode,
  FaLayerGroup,
  FaLeaf,
  FaLightbulb,
  FaLinkedinIn,
  FaLocationDot,
  FaLock,
  FaMagnifyingGlass,
  FaMicrochip,
  FaMicrosoft,
  FaMobileScreenButton,
  FaMoneyBillTrendUp,
  FaMusic,
  FaNodeJs,
  FaPaintbrush,
  FaPalette,
  FaPenNib,
  FaPeopleGroup,
  FaPhone,
  FaPhp,
  FaPlane,
  FaPython,
  FaQuoteLeft,
  FaReact,
  FaRobot,
  FaRocket,
  FaScrewdriverWrench,
  FaSeedling,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaStar,
  FaSwift,
  FaThumbsUp,
  FaTrophy,
  FaTruck,
  FaUpRightAndDownLeftFromCenter,
  FaUserCheck,
  FaUsers,
  FaUsersGear,
  FaUtensils,
  FaVuejs,
  FaWandMagicSparkles,
  FaWhatsapp,
  FaXTwitter,
  FaYoutube,
} = Fa6;

export const iconRegistry = {
  FaAndroid,
  FaAngular,
  FaArrowRight,
  FaArrowUpRightFromSquare,
  FaArrowsRotate,
  FaAward,
  FaAws,
  FaBolt,
  FaBoxesStacked,
  FaBrain,
  FaBriefcase,
  FaBuilding,
  FaBuildingColumns,
  FaBullhorn,
  FaBullseye,
  FaCalendarCheck,
  FaCamera,
  FaCar,
  FaCartShopping,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckDouble,
  FaCircleCheck,
  FaCirclePlay,
  FaClock,
  FaCloud,
  FaCode,
  FaComments,
  FaCss3Alt,
  FaCube,
  FaDatabase,
  FaDocker,
  FaDollarSign,
  FaEarthAmericas,
  FaEnvelope,
  FaEye,
  FaFacebookF,
  FaFeather,
  FaFilm,
  FaFire,
  FaFolderOpen,
  FaGamepad,
  FaGaugeHigh,
  FaGears,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGoogle,
  FaGraduationCap,
  FaHandPointer,
  FaHandshake,
  FaHeadset,
  FaHeart,
  FaHospital,
  FaHotel,
  FaHouse,
  FaHtml5,
  FaIndustry,
  FaInstagram,
  FaJava,
  FaJs,
  FaLaptopCode,
  FaLayerGroup,
  FaLeaf,
  FaLightbulb,
  FaLinkedinIn,
  FaLocationDot,
  FaLock,
  FaMagnifyingGlass,
  FaMicrochip,
  FaMicrosoft,
  FaMobileScreenButton,
  FaMoneyBillTrendUp,
  FaMusic,
  FaNodeJs,
  FaPaintbrush,
  FaPalette,
  FaPenNib,
  FaPeopleGroup,
  FaPhone,
  FaPhp,
  FaPlane,
  FaPython,
  FaQuoteLeft,
  FaReact,
  FaRobot,
  FaRocket,
  FaScrewdriverWrench,
  FaSeedling,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaStar,
  FaSwift,
  FaThumbsUp,
  FaTrophy,
  FaTruck,
  FaUpRightAndDownLeftFromCenter,
  FaUserCheck,
  FaUsers,
  FaUsersGear,
  FaUtensils,
  FaVuejs,
  FaWandMagicSparkles,
  FaWhatsapp,
  FaXTwitter,
  FaYoutube,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof iconRegistry;

export const iconNames = Object.keys(iconRegistry).sort() as IconName[];

export function isIconName(name: unknown): name is IconName {
  return typeof name === "string" && name in iconRegistry;
}

/** Unknown names fall back to a neutral mark rather than crashing a page. */
export function getIcon(name: string | undefined | null): IconType {
  if (isIconName(name)) {
    return iconRegistry[name];
  }
  return FaStar;
}
